"""initial_schema

Revision ID: dd614765567f
Revises: 
Create Date: 2026-09-30 09:23:29.391328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd614765567f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_address', sa.String(length=255), nullable=False),
    sa.Column('vasp_id', sa.String(length=100), nullable=False),
    sa.Column('vasp_name', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('hop_distance', sa.Integer(), nullable=False),
    sa.Column('interaction_count', sa.Integer(), nullable=True),
    sa.Column('total_volume', sa.Float(), nullable=True),
    sa.Column('score_breakdown', sa.JSON(), nullable=True),
    sa.Column('evidence_list', sa.JSON(), nullable=True),
    sa.Column('supporting_transactions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attributions_id'), 'attributions', ['id'], unique=False)
    op.create_index(op.f('ix_attributions_vasp_id'), 'attributions', ['vasp_id'], unique=False)
    op.create_index(op.f('ix_attributions_wallet_address'), 'attributions', ['wallet_address'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('case_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_username'), 'audit_logs', ['username'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.String(length=100), nullable=False),
    sa.Column('case_id', sa.String(length=100), nullable=True),
    sa.Column('wallet_address', sa.String(length=255), nullable=True),
    sa.Column('transaction_hash', sa.String(length=255), nullable=True),
    sa.Column('evidence_type', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('data_payload', sa.JSON(), nullable=True),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_case_id'), 'evidence', ['case_id'], unique=False)
    op.create_index(op.f('ix_evidence_evidence_id'), 'evidence', ['evidence_id'], unique=True)
    op.create_index(op.f('ix_evidence_id'), 'evidence', ['id'], unique=False)
    op.create_index(op.f('ix_evidence_wallet_address'), 'evidence', ['wallet_address'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.String(length=100), nullable=False),
    sa.Column('case_id', sa.String(length=100), nullable=False),
    sa.Column('wallet_address', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('sha256_hash', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('generated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_case_id'), 'reports', ['case_id'], unique=False)
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_report_id'), 'reports', ['report_id'], unique=True)
    op.create_index(op.f('ix_reports_wallet_address'), 'reports', ['wallet_address'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_address', sa.String(length=255), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('signals', sa.JSON(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessments_id'), 'risk_assessments', ['id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_wallet_address'), 'risk_assessments', ['wallet_address'], unique=False)
    op.create_table('sahyog_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=False),
    sa.Column('case_id', sa.String(length=100), nullable=False),
    sa.Column('vasp_id', sa.String(length=100), nullable=False),
    sa.Column('vasp_name', sa.String(length=255), nullable=False),
    sa.Column('wallet_address', sa.String(length=255), nullable=False),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('requested_info', sa.JSON(), nullable=True),
    sa.Column('supporting_evidence', sa.JSON(), nullable=True),
    sa.Column('mock_response', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sahyog_requests_case_id'), 'sahyog_requests', ['case_id'], unique=False)
    op.create_index(op.f('ix_sahyog_requests_id'), 'sahyog_requests', ['id'], unique=False)
    op.create_index(op.f('ix_sahyog_requests_reference_number'), 'sahyog_requests', ['reference_number'], unique=True)
    op.create_index(op.f('ix_sahyog_requests_vasp_id'), 'sahyog_requests', ['vasp_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_hash', sa.String(length=255), nullable=False),
    sa.Column('chain', sa.String(length=50), nullable=False),
    sa.Column('from_address', sa.String(length=255), nullable=False),
    sa.Column('to_address', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('token', sa.String(length=50), nullable=True),
    sa.Column('token_symbol', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=True),
    sa.Column('transaction_type', sa.String(length=50), nullable=True),
    sa.Column('gas', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('contract_address', sa.String(length=255), nullable=True),
    sa.Column('token_decimals', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tx_chain_time', 'transactions', ['chain', 'timestamp'], unique=False)
    op.create_index('idx_tx_from_to', 'transactions', ['from_address', 'to_address'], unique=False)
    op.create_index(op.f('ix_transactions_from_address'), 'transactions', ['from_address'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_to_address'), 'transactions', ['to_address'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_hash'), 'transactions', ['transaction_hash'], unique=True)
    op.create_table('typology_detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_address', sa.String(length=255), nullable=False),
    sa.Column('case_id', sa.String(length=100), nullable=True),
    sa.Column('pattern_type', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('supporting_txs', sa.JSON(), nullable=True),
    sa.Column('explanation', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_typology_detections_id'), 'typology_detections', ['id'], unique=False)
    op.create_index(op.f('ix_typology_detections_wallet_address'), 'typology_detections', ['wallet_address'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('badge_number', sa.String(length=50), nullable=True),
    sa.Column('agency', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'INVESTIGATOR', 'SUPERVISOR', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('vasps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vasp_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('compliance_email', sa.String(length=255), nullable=True),
    sa.Column('risk_category', sa.String(length=50), nullable=True),
    sa.Column('verification_status', sa.Enum('VERIFIED', 'PUBLICLY_REPORTED', 'UNVERIFIED', 'DEMO', name='verificationstatus'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vasps_id'), 'vasps', ['id'], unique=False)
    op.create_index(op.f('ix_vasps_vasp_id'), 'vasps', ['vasp_id'], unique=True)
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('blockchain', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_received', sa.Float(), nullable=True),
    sa.Column('total_sent', sa.Float(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('tx_count', sa.Integer(), nullable=True),
    sa.Column('is_monitored', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallets_address'), 'wallets', ['address'], unique=True)
    op.create_index(op.f('ix_wallets_id'), 'wallets', ['id'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('investigator_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='casepriority'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_ANALYSIS', 'REVIEW', 'CLOSED', name='casestatus'), nullable=False),
    sa.Column('suspect_wallets', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['investigator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_case_id'), 'cases', ['case_id'], unique=True)
    op.create_index(op.f('ix_cases_id'), 'cases', ['id'], unique=False)
    op.create_table('vasp_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vasp_id', sa.String(length=100), nullable=False),
    sa.Column('blockchain', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('address_type', sa.Enum('HOT_WALLET', 'DEPOSIT_WALLET', 'WITHDRAWAL_WALLET', 'CUSTODIAL_WALLET', 'CONTRACT', 'OTHER', name='addresstype'), nullable=False),
    sa.Column('label_source', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('verification_status', sa.Enum('VERIFIED', 'PUBLICLY_REPORTED', 'UNVERIFIED', 'DEMO', name='verificationstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['vasp_id'], ['vasps.vasp_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vasp_addresses_address'), 'vasp_addresses', ['address'], unique=False)
    op.create_index(op.f('ix_vasp_addresses_id'), 'vasp_addresses', ['id'], unique=False)
    op.create_index(op.f('ix_vasp_addresses_vasp_id'), 'vasp_addresses', ['vasp_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vasp_addresses_vasp_id'), table_name='vasp_addresses')
    op.drop_index(op.f('ix_vasp_addresses_id'), table_name='vasp_addresses')
    op.drop_index(op.f('ix_vasp_addresses_address'), table_name='vasp_addresses')
    op.drop_table('vasp_addresses')
    op.drop_index(op.f('ix_cases_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_case_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_address'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_vasps_vasp_id'), table_name='vasps')
    op.drop_index(op.f('ix_vasps_id'), table_name='vasps')
    op.drop_table('vasps')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_typology_detections_wallet_address'), table_name='typology_detections')
    op.drop_index(op.f('ix_typology_detections_id'), table_name='typology_detections')
    op.drop_table('typology_detections')
    op.drop_index(op.f('ix_transactions_transaction_hash'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_to_address'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_from_address'), table_name='transactions')
    op.drop_index('idx_tx_from_to', table_name='transactions')
    op.drop_index('idx_tx_chain_time', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_sahyog_requests_vasp_id'), table_name='sahyog_requests')
    op.drop_index(op.f('ix_sahyog_requests_reference_number'), table_name='sahyog_requests')
    op.drop_index(op.f('ix_sahyog_requests_id'), table_name='sahyog_requests')
    op.drop_index(op.f('ix_sahyog_requests_case_id'), table_name='sahyog_requests')
    op.drop_table('sahyog_requests')
    op.drop_index(op.f('ix_risk_assessments_wallet_address'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_id'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index(op.f('ix_reports_wallet_address'), table_name='reports')
    op.drop_index(op.f('ix_reports_report_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_case_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_evidence_wallet_address'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_evidence_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_case_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_audit_logs_username'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_attributions_wallet_address'), table_name='attributions')
    op.drop_index(op.f('ix_attributions_vasp_id'), table_name='attributions')
    op.drop_index(op.f('ix_attributions_id'), table_name='attributions')
    op.drop_table('attributions')
    # ### end Alembic commands ###
