import os
import hashlib
from datetime import datetime, timezone
from io import BytesIO
from typing import Dict, Any, List, Optional
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
)
from reportlab.pdfgen import canvas
from backend.app.config import settings

class NumberedCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_footer(num_pages)
            super().showPage()
        super().save()

    def draw_footer(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748b"))
        # Header rule
        self.setStrokeColor(colors.HexColor("#cbd5e1"))
        self.setLineWidth(0.5)
        self.line(40, letter[1] - 35, letter[0] - 40, letter[1] - 35)
        self.drawString(40, letter[1] - 30, "TraceVASP — Blockchain Intelligence & VASP Attribution Platform")
        self.drawRightString(letter[0] - 40, letter[1] - 30, "CONFIDENTIAL / LAW ENFORCEMENT SENSITIVE")

        # Footer
        self.line(40, 45, letter[0] - 40, 45)
        self.drawString(40, 32, "Generated by TraceVASP • For authorized investigative use only")
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(letter[0] - 40, 32, page_text)
        self.restoreState()

class ReportGenerator:
    @staticmethod
    def generate_investigation_report(
        case_id: str,
        wallet_address: str,
        case_data: Dict[str, Any],
        attributions: List[Dict[str, Any]],
        risk_data: Dict[str, Any],
        typologies: List[Dict[str, Any]],
        transactions: List[Dict[str, Any]],
        investigator_name: str = "Insp. Rajesh Kumar",
        agency: str = "Cyber Crime Investigation Cell (CCIC)",
        output_path: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Generates a comprehensive 16-section law enforcement report as a PDF.
        """
        buffer = BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            leftMargin=40,
            rightMargin=40,
            topMargin=50,
            bottomMargin=55
        )

        styles = getSampleStyleSheet()

        title_style = ParagraphStyle(
            'ReportTitle',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=18,
            leading=22,
            textColor=colors.HexColor('#0f172a'),
            spaceAfter=4
        )
        subtitle_style = ParagraphStyle(
            'ReportSubtitle',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=10,
            leading=14,
            textColor=colors.HexColor('#475569'),
            spaceAfter=12
        )
        h1_style = ParagraphStyle(
            'SectionH1',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=12,
            leading=16,
            textColor=colors.HexColor('#1e293b'),
            spaceBefore=12,
            spaceAfter=6
        )
        body_style = ParagraphStyle(
            'BodyTextCustom',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=9,
            leading=13,
            textColor=colors.HexColor('#334155')
        )
        body_bold = ParagraphStyle(
            'BodyBoldCustom',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=9,
            leading=13,
            textColor=colors.HexColor('#1e293b')
        )
        code_style = ParagraphStyle(
            'CodeStyle',
            parent=styles['Normal'],
            fontName='Courier',
            fontSize=8,
            leading=10,
            textColor=colors.HexColor('#0f172a')
        )

        story = []

        # Title Block
        story.append(Paragraph("TRACEVASP INVESTIGATION REPORT", title_style))
        story.append(Paragraph("Automated Attribution of Cryptocurrency Wallets to Nearest VASPs", subtitle_style))
        story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#0284c7'), spaceAfter=12))

        # 1. Case Information
        story.append(Paragraph("1. Case Information", h1_style))
        case_info_data = [
            [Paragraph("Case ID:", body_bold), Paragraph(case_id, body_style), Paragraph("Priority:", body_bold), Paragraph(str(case_data.get('priority', 'HIGH')), body_style)],
            [Paragraph("Title:", body_bold), Paragraph(str(case_data.get('title', 'Cryptocurrency Flow Analysis')), body_style), Paragraph("Status:", body_bold), Paragraph(str(case_data.get('status', 'UNDER_ANALYSIS')), body_style)],
            [Paragraph("Investigator:", body_bold), Paragraph(investigator_name, body_style), Paragraph("Date Generated:", body_bold), Paragraph(datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"), body_style)],
            [Paragraph("Agency:", body_bold), Paragraph(agency, body_style), Paragraph("Data Source:", body_bold), Paragraph("Deterministic Demo / Intelligence Registry", body_style)],
        ]
        t_case = Table(case_info_data, colWidths=[90, 180, 85, 175])
        t_case.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#f8fafc')),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#e2e8f0')),
            ('PADDING', (0,0), (-1,-1), 5),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ]))
        story.append(t_case)
        story.append(Spacer(1, 10))

        # 2. Investigated Wallet & 3. Blockchain
        story.append(Paragraph("2. Investigated Wallet & 3. Blockchain Ledger", h1_style))
        wallet_table_data = [
            [Paragraph("Target Address:", body_bold), Paragraph(wallet_address, code_style)],
            [Paragraph("Blockchain:", body_bold), Paragraph("Ethereum Mainnet (EVM)", body_style)],
            [Paragraph("Entity Category:", body_bold), Paragraph("Unknown Target Wallet (Primary Suspect)", body_style)],
            [Paragraph("Monitored Status:", body_bold), Paragraph("Active Law Enforcement Watchlist", body_style)]
        ]
        t_wallet = Table(wallet_table_data, colWidths=[120, 410])
        t_wallet.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#ffffff')),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#cbd5e1')),
            ('PADDING', (0,0), (-1,-1), 4),
        ]))
        story.append(t_wallet)
        story.append(Spacer(1, 10))

        # 4. Transaction Summary & 5. Fund Flow
        story.append(Paragraph("4. Transaction Summary & 5. Fund Flow Traversal", h1_style))
        tx_count = len(transactions)
        total_vol = sum(t.get('amount', 0) for t in transactions)
        story.append(Paragraph(
            f"TraceVASP reconstructed a total of <b>{tx_count}</b> multi-hop transactions traversing across the suspect cluster, accounting for <b>{total_vol:.2f} ETH</b> in aggregate transaction volume. The predominant outflow path demonstrates rapid hops from the initial deposit through intermediary wallets into identifiable exchange deposit gateways.",
            body_style
        ))
        story.append(Spacer(1, 6))

        # Table of top 5 key flow transactions
        tx_headers = [Paragraph("<b>Tx Hash</b>", body_bold), Paragraph("<b>From</b>", body_bold), Paragraph("<b>To</b>", body_bold), Paragraph("<b>Amount</b>", body_bold), Paragraph("<b>Type</b>", body_bold)]
        tx_rows = [tx_headers]
        for tx in transactions[:6]:
            h_short = tx.get('transaction_hash', '')[:12] + "..."
            from_short = tx.get('from_address', '')[:8] + "..."
            to_short = tx.get('to_address', '')[:8] + "..."
            amt_str = f"{tx.get('amount', 0):.2f} {tx.get('token_symbol', 'ETH')}"
            tx_type = tx.get('transaction_type', 'TRANSFER')
            tx_rows.append([
                Paragraph(h_short, code_style),
                Paragraph(from_short, code_style),
                Paragraph(to_short, code_style),
                Paragraph(amt_str, body_style),
                Paragraph(tx_type, body_style)
            ])
        t_tx = Table(tx_rows, colWidths=[110, 105, 105, 110, 100])
        t_tx.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#f1f5f9')),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#e2e8f0')),
            ('PADDING', (0,0), (-1,-1), 4),
            ('ALIGN', (3,1), (3,-1), 'RIGHT'),
        ]))
        story.append(t_tx)
        story.append(Spacer(1, 10))

        # 6. Transaction Graph Summary
        story.append(Paragraph("6. Transaction Graph Architecture", h1_style))
        story.append(Paragraph(
            "Graph construction was executed using NetworkX multi-layer directed graph heuristics. The network topology includes the source suspect node, 2 intermediate layering hops, 1 privacy mixer interaction node, 1 cross-chain bridge gateway, and 2 separate VASP clusters.",
            body_style
        ))
        story.append(Spacer(1, 10))

        # 7. VASP Attribution & 8. Attribution Confidence
        story.append(Paragraph("7. VASP Attribution & 8. Attribution Confidence Scoring", h1_style))
        attr_headers = [
            Paragraph("<b>Candidate VASP</b>", body_bold),
            Paragraph("<b>Confidence</b>", body_bold),
            Paragraph("<b>Hop Distance</b>", body_bold),
            Paragraph("<b>Interactions</b>", body_bold),
            Paragraph("<b>Volume</b>", body_bold)
        ]
        attr_rows = [attr_headers]
        for a in attributions:
            conf_str = f"<b>{a.get('confidence', 0):.1f}%</b>"
            hops_str = f"{a.get('hop_distance', 0)} hops"
            attr_rows.append([
                Paragraph(str(a.get('vasp_name', 'Unknown VASP')), body_style),
                Paragraph(conf_str, body_style),
                Paragraph(hops_str, body_style),
                Paragraph(str(a.get('interaction_count', 0)), body_style),
                Paragraph(f"{a.get('total_volume', 0):.2f} ETH", body_style)
            ])
        t_attr = Table(attr_rows, colWidths=[150, 95, 95, 95, 95])
        t_attr.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#f1f5f9')),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#e2e8f0')),
            ('PADDING', (0,0), (-1,-1), 4),
        ]))
        story.append(t_attr)
        story.append(Spacer(1, 10))

        # 9. Supporting Evidence
        story.append(Paragraph("9. Supporting Attribution Evidence", h1_style))
        top_cand = attributions[0] if attributions else None
        if top_cand and top_cand.get('evidence'):
            for ev in top_cand.get('evidence', []):
                story.append(Paragraph(f"• {ev}", body_style))
        else:
            story.append(Paragraph("• Direct multi-hop path identified terminating in exchange deposit gateway.", body_style))
        story.append(Spacer(1, 10))

        # 10. Risk Analysis
        story.append(Paragraph("10. Risk Analysis (Analytical Indicators)", h1_style))
        risk_score = risk_data.get('risk_score', 0.0)
        risk_level = risk_data.get('risk_level', 'LOW')
        story.append(Paragraph(
            f"Overall Calculated Risk Score: <b>{risk_score}/100</b> (Classification: <b>{risk_level}</b>)",
            body_bold
        ))
        for sig in risk_data.get('signals', []):
            story.append(Paragraph(f"• [Indicator] {sig}", body_style))
        story.append(Spacer(1, 10))

        # 11. Detected Transaction Typologies
        story.append(Paragraph("11. Detected Transaction Typologies", h1_style))
        if typologies:
            for typ in typologies:
                ptype = typ.get('pattern_type', 'OBSERVED_PATTERN')
                conf = typ.get('confidence', 0)
                exp = typ.get('explanation', '')
                story.append(Paragraph(f"<b>[{ptype}]</b> — Confidence: {conf:.1f}%", body_bold))
                story.append(Paragraph(f"{exp}", body_style))
                story.append(Spacer(1, 3))
        else:
            story.append(Paragraph("No anomalous typologies detected.", body_style))
        story.append(Spacer(1, 10))

        # 12. Cross-Chain Activity
        story.append(Paragraph("12. Cross-Chain Activity & Bridge Analysis", h1_style))
        story.append(Paragraph(
            "Identified cross-chain liquidity interaction involving DemoBridge Protocol Gateway. While transactions on destination chains are recorded under separate ledgers, correlation timestamps suggest rapid off-network movement.",
            body_style
        ))
        story.append(Spacer(1, 10))

        # 13. Investigator Notes
        story.append(Paragraph("13. Investigator Notes", h1_style))
        story.append(Paragraph(
            str(case_data.get('notes', 'Preliminary evidence supports immediate initiation of Section 91 CrPC / Section 69 IT Act formal disclosure request to Demo Exchange Alpha compliance desk via SAHYOG portal adapter.')),
            body_style
        ))
        story.append(Spacer(1, 10))

        # 14. Data Sources
        story.append(Paragraph("14. Data Sources & Intelligence Provenance", h1_style))
        story.append(Paragraph(
            "Intelligence feeds: TraceVASP Curated VASP Registry, Local Node Indexers, Public Blockchain RPC, and Certified Test Fixtures.",
            body_style
        ))
        story.append(Spacer(1, 10))

        # 15. Evidence Integrity
        story.append(Paragraph("15. Evidence Integrity Verification (SHA-256)", h1_style))
        # Pre-compute document content hash
        story.append(Paragraph(
            "All supporting transaction hashes, attribution score records, and case logs have been digitally signed with cryptographic SHA-256 hashes to ensure chain of custody for courtroom presentation under Indian Evidence Act Section 65B.",
            body_style
        ))
        story.append(Spacer(1, 10))

        # 16. Disclaimer
        story.append(Paragraph("16. Formal Disclaimer", h1_style))
        story.append(Paragraph(
            "This report is generated automatically by TraceVASP for intelligence and investigative assistance. Attribution scores and risk indicators are analytical probabilities derived from graph traversal algorithms and do not represent a final judicial determination of criminal liability.",
            body_style
        ))

        # Build document
        doc.build(story, canvasmaker=NumberedCanvas)
        pdf_bytes = buffer.getvalue()
        buffer.close()

        pdf_hash = hashlib.sha256(pdf_bytes).hexdigest()

        # If output_path provided, save to disk
        if not output_path:
            os.makedirs(settings.REPORT_DIR, exist_ok=True)
            output_path = os.path.join(settings.REPORT_DIR, f"{case_id}_{wallet_address[:10]}.pdf")

        with open(output_path, "wb") as f:
            f.write(pdf_bytes)

        return {
            "file_path": output_path,
            "sha256_hash": pdf_hash,
            "size_bytes": len(pdf_bytes)
        }
